version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: memory_site
      MYSQL_USER: root
      MYSQL_PASSWORD: "123"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_backup.sql:/docker-entrypoint-initdb.d/mysql_backup.sql
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_web
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql_web;Database=memory_site;User=root;Password=123;
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
